name: uichatapp
description: A new Flutter chat application
version: 1.0.0+1

environment:
  sdk: "^3.5.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
